version: "2.11"
services:
  openmeeting:
    image: apache/openmeetings:7.2.0
    ports: 
      - 5080:5080
    volumes:
      - /home/user/project/:/opt/omdata
    networks:
      myMACvlan:
          ipv4_address: 192.168.1.20
networks:
  myMACvlan:
    driver: bridge # Если пишу macvlan не работает
    driver_opts:
      parent: enp0s3
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"


